# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newMsBooksProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='newMsBooksProto.proto',
  package='MassoudBookSerialization',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15newMsBooksProto.proto\x12\x18MassoudBookSerialization\"i\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tagory\x18\x02 \x01(\t\x12\x15\n\rreadingStatus\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\r\n\x05pages\x18\x05 \x01(\x05\x12\r\n\x05notes\x18\x06 \x03(\t\"\x91\x01\n\x05\x42ooks\x12\x30\n\x08\x41llBooks\x18\x01 \x03(\x0b\x32\x1e.MassoudBookSerialization.Book\x12\x0f\n\x07\x41llTags\x18\x02 \x03(\t\x12\x15\n\rAllCatagories\x18\x03 \x03(\t\x12\x18\n\x10\x41llReadingStatus\x18\x04 \x03(\t\x12\x14\n\x0cGeneralNotes\x18\x05 \x03(\tb\x06proto3')
)




_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='MassoudBookSerialization.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MassoudBookSerialization.Book.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='catagory', full_name='MassoudBookSerialization.Book.catagory', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readingStatus', full_name='MassoudBookSerialization.Book.readingStatus', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='MassoudBookSerialization.Book.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pages', full_name='MassoudBookSerialization.Book.pages', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='MassoudBookSerialization.Book.notes', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=156,
)


_BOOKS = _descriptor.Descriptor(
  name='Books',
  full_name='MassoudBookSerialization.Books',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AllBooks', full_name='MassoudBookSerialization.Books.AllBooks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllTags', full_name='MassoudBookSerialization.Books.AllTags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllCatagories', full_name='MassoudBookSerialization.Books.AllCatagories', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AllReadingStatus', full_name='MassoudBookSerialization.Books.AllReadingStatus', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GeneralNotes', full_name='MassoudBookSerialization.Books.GeneralNotes', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=304,
)

_BOOKS.fields_by_name['AllBooks'].message_type = _BOOK
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['Books'] = _BOOKS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(
  DESCRIPTOR = _BOOK,
  __module__ = 'newMsBooksProto_pb2'
  # @@protoc_insertion_point(class_scope:MassoudBookSerialization.Book)
  ))
_sym_db.RegisterMessage(Book)

Books = _reflection.GeneratedProtocolMessageType('Books', (_message.Message,), dict(
  DESCRIPTOR = _BOOKS,
  __module__ = 'newMsBooksProto_pb2'
  # @@protoc_insertion_point(class_scope:MassoudBookSerialization.Books)
  ))
_sym_db.RegisterMessage(Books)


# @@protoc_insertion_point(module_scope)
